{ pkgs
, lib
, config
, ...
}:
let
  cfg = config.services.lnd;
  bitcoind = config.services.bitcoind;
  types = lib.types;

  lncliCmd = ''
    ${lib.getExe' cfg.package "lncli"} \
      --network ${cfg.network} \
      --rpcserver=${cfg.rpcAddress}:${toString cfg.rpcPort} \
      --lnddir="${cfg.dataDir}" \
      --tlscertpath="${cfg.certFile}" \
      --macaroonpath="${cfg.macaroonFile}"'';


  configFile = pkgs.writeText "lnd.conf" (''
    datadir=${cfg.dataDir}
    tlscertpath=${cfg.dataDir}/tls.cert
    tlskeypath=${cfg.dataDir}/tls.key
    noseedbackup=1

    listen=${cfg.listenAddress}:${toString cfg.listenPort}
    rpclisten=${cfg.rpcAddress}:${toString cfg.rpcPort}
    restlisten=${cfg.restAddress}:${toString cfg.restPort}

    debuglevel=info

    bitcoin.active=1
    bitcoin.node=bitcoind
  '' + lib.optionalString bitcoind.regtest ''
    bitcoin.regtest=1
  '' + ''

    bitcoind.rpchost=${bitcoind.rpcAddress}:${toString bitcoind.rpcPort}
    bitcoind.rpcuser=${bitcoind.rpcUser}
    bitcoind.rpcpass=${bitcoind.rpcPassword}
    bitcoind.zmqpubrawblock=${bitcoind.zmq.pubrawblock}
    bitcoind.zmqpubrawtx=${bitcoind.zmq.pubrawtx}
  '' + cfg.extraConfig);
in
{
  options.services.lnd = {
    enable = lib.mkEnableOption "Lightning Network daemon";

    package = lib.mkOption {
      type = types.package;
      default = pkgs.lnd;
      description = "The lnd package to use.";
    };

    dataDir = lib.mkOption {
      type = types.str;
      default = "${config.devenv.state}/lnd";
      description = "Data directory for lnd.";
    };

    listenAddress = lib.mkOption {
      type = types.str;
      default = "127.0.0.1";
      description = "Address to listen for peer connections.";
    };

    listenPort = lib.mkOption {
      type = types.port;
      default = 9735;
      description = "Port to listen for peer connections.";
    };

    rpcAddress = lib.mkOption {
      type = types.str;
      default = "127.0.0.1";
      description = "Address to listen for gRPC connections.";
    };

    rpcPort = lib.mkOption {
      type = types.port;
      default = 10009;
      description = "Port to listen for gRPC connections.";
    };

    restAddress = lib.mkOption {
      type = types.str;
      default = "127.0.0.1";
      description = "Address to listen for REST connections.";
    };

    restPort = lib.mkOption {
      type = types.port;
      default = 8080;
      description = "Port to listen for REST connections.";
    };

    extraConfig = lib.mkOption {
      type = types.lines;
      default = "";
      description = "Extra lines appended to lnd.conf.";
    };

    # Read-only derived fields — LND itself fixes these paths based on
    # `dataDir` and the active network, so downstream modules (e.g.
    # services.lnbits.backends.lnd) can reference them without reproducing
    # the derivation.
    network = lib.mkOption {
      type = types.str;
      readOnly = true;
      default = if bitcoind.regtest then "regtest" else "mainnet";
      defaultText = lib.literalExpression ''if config.services.bitcoind.regtest then "regtest" else "mainnet"'';
      description = "Active chain network (regtest/mainnet), derived from services.bitcoind.regtest.";
    };

    certFile = lib.mkOption {
      type = types.str;
      readOnly = true;
      default = "${cfg.dataDir}/tls.cert";
      defaultText = lib.literalExpression ''"''${cfg.dataDir}/tls.cert"'';
      description = "Path to the TLS certificate generated by lnd.";
    };

    macaroonFile = lib.mkOption {
      type = types.str;
      readOnly = true;
      default = "${cfg.dataDir}/chain/bitcoin/${cfg.network}/admin.macaroon";
      defaultText = lib.literalExpression ''"''${cfg.dataDir}/chain/bitcoin/''${cfg.network}/admin.macaroon"'';
      description = "Path to the admin macaroon generated by lnd under the active network.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.bitcoind = {
      enable = true;
      zmq.enable = lib.mkDefault true;
    };

    packages = [
      cfg.package
    ];

    env.LND_CERT_FILE = cfg.certFile;
    env.LND_MACAROON_FILE = cfg.macaroonFile;
    env.LND_GRPC_HOST = "https://${cfg.rpcAddress}:${toString cfg.rpcPort}";

    processes.lnd = {
      after = [ "devenv:processes:bitcoind" ];
      exec = lib.getExe (
        pkgs.writeShellApplication {
          name = "lnd-start";
          runtimeInputs = [ cfg.package ];
          text = ''
            mkdir -p "${cfg.dataDir}"
            exec lnd --configfile="${configFile}"
          '';
        }
      );
      ready = {
        exec = ''
          test -f "${cfg.macaroonFile}" && ${lncliCmd} getinfo > /dev/null 2>&1
        '';
        period = 2;
        failure_threshold = 30;
      };
      process-compose = {
        readiness_probe = {
          exec = {
            command = pkgs.writeShellScript "is-lnd-ready" ''
              test -f "${cfg.macaroonFile}" && ${lncliCmd} getinfo > /dev/null 2>&1
            '';
          };
          failure_threshold = 30;
          period_seconds = 2;
        };
        depends_on.bitcoind.condition = "process_healthy";
        shutdown = {
          command = ''
            ${lncliCmd} stop
          '';
          timeout_seconds = 30;
        };
      };
    };
  };
}
