name: Run devenv tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: NixOS/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Run tests
        run: devenv-run-tests run tests
